[package]
name = "BitRust"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0"
hex = "0.4"
sha2 = "0.10"
base58 = "0.2"
num-bigint = "0.4"
num-traits = "0.2"
secp256k1 = "0.24"
digest = "0.9"
ripemd160 = "0.9"
rand = "0.8"